throw new Exception("target exception");